# Generated by Django 4.1 on 2022-09-30 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTextil', '0004_rename_userid_registro_contable_idusuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='registro_id',
        ),
    ]
