# Generated by Django 4.1 on 2022-09-30 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTextil', '0005_remove_empleado_registro_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='usuario_id',
            new_name='usuarid',
        ),
    ]
